# First Play
- name: Play - Handle Files in all hosts
  hosts: all
  tasks:
  - name: all host are identified with a file
    copy:
      content: My family is {{ ansible_os_family }}
      dest: /family.txt
      mode: '777'

## Second play
- name: Play - for Alpines Nodejs app
  hosts: app_group
  tasks:
  - name: Update Alpine package cache
    apk:
      update_cache: yes

  - name: Install Node.js and npm
    apk:
      name:
        - nodejs
        - npm  # Fix: Install npm separately
      state: latest

  - name: app directory is created
    file:
      path: /node-app
      state: directory

  - name: app is installed
    template:
      src: app.js.j2
      dest: /node-app/app.js

  - name: app dependencies file is copied
    copy:
      src: package.json
      dest: /node-app/package.json

  - name: app dependencies are installed
    npm:
      path: /node-app
      state: present
      production: true

  - name: Install `forever` globally (to keep app running)
    npm:
      name: forever
      global: yes
      state: present

  - name: Check list of running Node.js apps
    command: forever list
    register: forever_list
    changed_when: false

  - name: Start example Node.js app
    command: forever start /node-app/app.js
    when: "forever_list.stdout.find('/node-app/app.js') == -1"
